"""
Graph for figure 3
The graph is an adjacency list with (neighbour, backward_cost) tuples.
"""

# ── Weighted adjacency list (backward costs) ──
figure3_graph = {
    # ── Northern Region ──
    "Kartum": [("Humera", 21), ("Metema", 19)],
    "Asmera": [("Adwa", 6), ("Adigrat", 9)],
    "Humera": [("Kartum", 21), ("Shire", 8), ("Gondar", 9)],
    "Shire": [("Humera", 8), ("Axum", 2), ("Adwa", 7)],
    "Axum": [("Shire", 2), ("Adwa", 1), ("Adigrat", 4)],
    "Adwa": [("Axum", 1), ("Adigrat", 2), ("Asmera", 6), ("Shire", 7)],
    "Adigrat": [("Adwa", 2), ("Asmera", 9), ("Axum", 4), ("Mekelle", 4)],
    "Debarke": [("Shire", 7), ("Gondar", 4)],
    "Mekelle": [("Adigrat", 4), ("Sekota", 9), ("Alamata", 5), ("Kilbet Rasu", 8)],
    "Sekota": [("Mekelle", 9), ("Alamata", 6), ("Lalibela", 6), ("Debre Tabor", 8)],
    "Alamata": [("Mekelle", 5), ("Sekota", 6), ("Woldia", 3), ("Dessie", 8), ("Samara", 11)],

    # ── Afar / North-East ──
    "Samara": [("Woldia", 8), ("Alamata", 11), ("Gabi Rasu", 10), ("Fenti Rasu", 7)],
    "Fenti Rasu": [("Samara", 7), ("Kilbet Rasu", 6)],
    "Kilbet Rasu": [("Fenti Rasu", 6), ("Mekelle", 8)],
    "Gabi Rasu": [("Samara", 10), ("Awash", 5)],

    # ── North-West ──
    "Metema": [("Kartum", 19), ("Gondar", 7), ("Azezo", 7)],
    "Gondar": [("Humera", 9), ("Azezo", 1), ("Debarke", 4), ("Metema", 7), ("Debre Tabor", 6), ("Bahir Dar", 11)],
    "Azezo": [("Gondar", 1), ("Metema", 7), ("Bahir Dar", 7)],
    "Bahir Dar": [("Azezo", 7), ("Debre Tabor", 4), ("Injibara", 4), ("Metekel", 11), ("Gondar", 11)],
    "Debre Tabor": [("Bahir Dar", 4), ("Lalibela", 8), ("Sekota", 8), ("Gondar", 6)],
    "Lalibela": [("Debre Tabor", 8), ("Woldia", 7), ("Sekota", 6), ("Dessie", 12)],
    "Woldia": [("Lalibela", 7), ("Alamata", 3), ("Dessie", 6), ("Samara", 8)],

    # ── Central-West ──
    "Metekel": [("Bahir Dar", 11), ("Assosa", 11), ("Injibara", 6)],
    "Assosa": [("Metekel", 11), ("Gimbi", 8)],
    "Injibara": [("Bahir Dar", 4), ("Metekel", 6), ("Finote Selam", 2)],
    "Finote Selam": [("Injibara", 2), ("Debre Markos", 3), ("Bahir Dar", 6)],
    "Debre Markos": [("Finote Selam", 3), ("Debre Sina", 17)],

    # ── Central ──
    "Dessie": [("Woldia", 6), ("Kemise", 4), ("Alamata", 8), ("Lalibela", 12)],
    "Kemise": [("Dessie", 4), ("Debre Sina", 6)],
    "Debre Sina": [("Kemise", 6), ("Debre Birhan", 2), ("Debre Markos", 17)],
    "Debre Birhan": [("Debre Sina", 2), ("Addis Ababa", 5)],
    "Addis Ababa": [("Debre Birhan", 5), ("Debre Markos", 13), ("Ambo", 5), ("Adama", 3)],

    # ── West ──
    "Ambo": [("Addis Ababa", 5), ("Nekemte", 8)],
    "Nekemte": [("Ambo", 8), ("Gimbi", 4), ("Bedelle", 5)],
    "Gimbi": [("Nekemte", 4), ("Dembi Dollo", 6), ("Assosa", 8)],
    "Dembi Dollo": [("Gimbi", 6), ("Gambella", 4)],
    "Gambella": [("Dembi Dollo", 4), ("Gore", 5)],
    "Gore": [("Gambella", 5), ("Tepi", 9), ("Bedelle", 6)],
    "Bedelle": [("Nekemte", 5), ("Gore", 6), ("Jimma", 7)],

    # ── East ──
    "Adama": [("Addis Ababa", 3), ("Matahara", 3), ("Asella", 4), ("Batu", 4)],
    "Matahara": [("Adama", 3), ("Awash", 1)],
    "Awash": [("Matahara", 1), ("Gabi Rasu", 5), ("Chiro", 4)],
    "Chiro": [("Awash", 4), ("Dire Dawa", 8)],
    "Dire Dawa": [("Chiro", 8), ("Harar", 4)],
    "Harar": [("Dire Dawa", 4), ("Babile", 2)],
    "Babile": [("Harar", 2), ("Jigjiga", 3), ("Gode", 28)],
    "Jigjiga": [("Babile", 3), ("Dega Habur", 5)],
    "Dega Habur": [("Jigjiga", 5), ("Kebri Dehar", 6), ("Gode", 17)],
    "Kebri Dehar": [("Dega Habur", 6), ("Werder", 6), ("Gode", 5)],
    "Werder": [("Kebri Dehar", 6)],
    "Gode": [("Kebri Dehar", 5), ("Sof Oumer", 23), ("Dollo", 17), ("Babile", 28), ("Dega Habur", 17), ("Mokadisho", 22)],
    "Dollo": [("Gode", 17), ("Liben", 11), ("Moyale", 18)],
    "Mokadisho": [("Gode", 22), ("Moyale", 40)],

    # ── South-East ──
    "Sof Oumer": [("Gode", 23), ("Goba", 6), ("Bale", 23)],
    "Goba": [("Sof Oumer", 6), ("Bale", 18), ("Dodolla", 5)],
    "Bale": [("Goba", 18), ("Sof Oumer", 23), ("Liben", 11)],
    "Liben": [("Bale", 11), ("Dollo", 11), ("Moyale", 11)],
    "Dodolla": [("Goba", 5), ("Assasa", 1), ("Shashemene", 3), ("Robe", 13)],
    "Robe": [("Dodolla", 13), ("Goba", 18), ("Liben", 11)],
    "Assasa": [("Dodolla", 1), ("Asella", 4)],
    "Asella": [("Assasa", 4), ("Adama", 4)],

    # ── South / Central ──
    "Batu": [("Adama", 4), ("Butajira", 2), ("Shashemene", 3)],
    "Butajira": [("Batu", 2), ("Worabe", 2), ("Wolkite", 4)],
    "Worabe": [("Butajira", 2), ("Hossana", 2), ("Wolkite", 5)],
    "Wolkite": [("Worabe", 5), ("Butajira", 4), ("Ambo", 6), ("Jimma", 8), ("Hossana", 5)],
    "Hossana": [("Worabe", 2), ("Shashemene", 7), ("Wolaita Sodo", 4), ("Wolkite", 5)],
    "Wolaita Sodo": [("Hossana", 4), ("Dawro", 6), ("Arba Minch", 4), ("Jimma", 10)],
    "Shashemene": [("Batu", 3), ("Dodolla", 3), ("Hossana", 7), ("Hawassa", 1)],
    "Hawassa": [("Shashemene", 1), ("Dilla", 3)],
    "Dilla": [("Hawassa", 3), ("Bule Hora", 7)],
    "Bule Hora": [("Dilla", 7), ("Yabello", 3)],
    "Yabello": [("Bule Hora", 3), ("Konso", 3), ("Moyale", 6)],
    "Konso": [("Yabello", 3), ("Arba Minch", 4)],
    "Arba Minch": [("Konso", 4), ("Wolaita Sodo", 4), ("Basketo", 10)],
    "Moyale": [("Yabello", 6), ("Nairobi", 22), ("Liben", 11), ("Dollo", 18), ("Mokadisho", 40)],
    "Nairobi": [("Moyale", 22)],

    # ── South-West ──
    "Dawro": [("Wolaita Sodo", 6), ("Basketo", 4), ("Bonga", 10)],
    "Basketo": [("Dawro", 4), ("Arba Minch", 10), ("Bench Maji", 5), ("Konso", 10), ("Mizan Teferi", 7)],
    "Bonga": [("Dawro", 10), ("Jimma", 4), ("Tepi", 8), ("Mizan Teferi", 4)],
    "Jimma": [("Bonga", 4), ("Bedelle", 7), ("Wolkite", 8), ("Wolaita Sodo", 10)],
    "Tepi": [("Gore", 9), ("Bonga", 8), ("Mizan Teferi", 4)],
    "Mizan Teferi": [("Tepi", 4), ("Bonga", 4), ("Basketo", 7)],
    "Bench Maji": [("Basketo", 5), ("Juba", 22)],
    "Juba": [("Bench Maji", 22)],
}

# ── Heuristic values h(n) — estimated distance to Moyale ──
figure3_heuristics = {
    "Kartum": 81,
    "Asmera": 68,
    "Humera": 65,
    "Shire": 67,
    "Axum": 66,
    "Adwa": 65,
    "Adigrat": 62,
    "Mekelle": 58,
    "Sekota": 59,
    "Metema": 62,
    "Azezo": 55,
    "Gondar": 56,
    "Debre Tabor": 52,
    "Bahir Dar": 48,
    "Metekel": 59,
    "Assosa": 51,
    "Lalibela": 47,
    "Woldia": 50,
    "Alamata": 53,
    "Kilbet Rasu": 55,
    "Fenti Rasu": 49,
    "Samara": 42,
    "Gabi Rasu": 32,
    "Dessie": 44,
    "Kemise": 40,
    "Debre Sina": 33,
    "Debre Birhan": 31,
    "Finote Selam": 42,
    "Injibara": 44,
    "Debre Markos": 39,
    "Addis Ababa": 26,
    "Ambo": 31,
    "Nekemte": 39,
    "Gimbi": 43,
    "Dembi Dollo": 49,
    "Gambella": 51,
    "Gore": 46,
    "Bedelle": 40,
    "Tepi": 41,
    "Mizan Teferi": 37,
    "Bonga": 33,
    "Jimma": 33,
    "Wolkite": 25,
    "Butajira": 25,
    "Worabe": 22,
    "Hossana": 21,
    "Wolaita Sodo": 17,
    "Dawro": 23,
    "Arba Minch": 13,
    "Basketo": 23,
    "Bench Maji": 28,
    "Juba": 50,
    "Konso": 9,
    "Yabello": 6,
    "Bule Hora": 8,
    "Dilla": 12,
    "Hawassa": 15,
    "Shashemene": 16,
    "Batu": 19,
    "Adama": 23,
    "Matahara": 36,
    "Awash": 27,
    "Chiro": 31,
    "Dire Dawa": 31,
    "Harar": 35,
    "Babile": 37,
    "Jigjiga": 40,
    "Dega Habur": 45,
    "Kebri Dehar": 40,
    "Werder": 46,
    "Gode": 35,
    "Sof Oumer": 45,
    "Goba": 40,
    "Robe": 22,
    "Dodolla": 19,
    "Assasa": 18,
    "Asella": 22,
    "Liben": 11,
    "Dollo": 18,
    "Mokadisho": 40,
    "Moyale": 0,
    "Nairobi": 22,
    "Debarke": 60,
    "Bale": 22,
}
